apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: observability
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:REdeEFbbkd1/zULFCEQTxS5N/l0PVcb4S5FF/Yik3LjH3fJ4ZZSAI/xsPkvvGpxQ8mUz99LxVFTVPMCDm4snGR6PgEmipMhISbqr5uqqeSKhGW3YvkqGmbYceAyRYPeNr6wEZ0wzeHLXHawsVV549kH/fMN0iTtPeQ==,iv:UptwjBrE++V4xXxgvVLctFPwOKjI/v85zXK4UTRLTrY=,tag:sXPdv4dkgeS5cdbxF6zKng==,type:str]
sops:
  age:
    - recipient: age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSWZhWEgwKzM1Uk5ocEhq
        Z2E1TldZSE5vaEwvRS9wNk1kTm81bmh5NzNRCngwYzR3QUNnVlBod25kZTNBNFZH
        cVFOSGVlVUIvc2hIT2Fnc3c4WVhjTU0KLS0tIFU1K2ZGNlhjc0RMVllBbDRKa1VF
        WEpkbnJUMUFJbm5aR292NFh6U01PVHMKk4hc6nAg3oGcavTD0pIlM9K5cv2MqTJq
        sAhDK46pMqFhQ6AUjfP9gx1cxdu8qAD8lZ9RNme8rcB7MT9AlL8Z9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T20:25:58Z"
  mac: ENC[AES256_GCM,data:x0DubwFjNAqUHEg+KxOJ5MSxIC7yJiGUkaAY1ijER7Ubynme3NpKsyE9+nTc+kdEyfHhp2IMlhqGKTjQ7iJrGFm+JZUHS115KPb3qh49AaTk03FDaFHBHcKWHcmfV4yrjUtMbIZpfk+YRvlHMpcP/qluCyUz9lCsBwOz+aicp2U=,iv:kxl36vgzAdLqVZD0is4n0KZFL/eo27WCamlAC7a3M5M=,tag:KssjQV6F2Pq3yfGITnEtbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
