---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux"
stores:
  yaml:
    indent: 2
