---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pihole-node
  labels:
    release: kube-prometheus-stack
spec:
  jobName: pihole-node
  scrapeInterval: 30s
  metricsPath: /metrics
  scheme: HTTP
  staticConfigs:
    - targets:
        - 192.168.1.40:9100
      labels:
        instance: pi-hole.lan
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pihole-exporter
  labels:
    release: kube-prometheus-stack
spec:
  jobName: pihole-exporter
  scrapeInterval: 30s
  metricsPath: /metrics
  scheme: HTTP
  staticConfigs:
    - targets:
        - 192.168.1.40:9617
      labels:
        instance: pi-hole.lan
